version: '3.8'

services:
  api:
    user: root
    container_name: storage_app_api
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    restart: on-failure:3
    ports:
    - 3001:3000
    environment:
    # We want the following to be always picked from docker compose and not modified by developer
      - TIME_ZONE=Etc/Universal
      - SECRET_KEY_BASE=e769ca93ff1fcd78449c85d8adeb98a6
      - DB_NAME=storage_app
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    # Any extra environment variables  
    # env_file:
    #   - ../.env
    volumes:
      - .:/rails
      # - ../package.json:/home/node/package.json
    depends_on:
      - db
      - test-db

  db:
    container_name: storage_app_db
    image: postgres:14
    restart: on-failure:3
    ports:
      - 15432:5432
    environment:
      - POSTGRES_DB=storage_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  test-db:
      container_name: storage_app_db_test
      image: postgres:14
      ports:
        - 25432:5432
      restart: always
      environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ctb_api_test

  redis:
    container_name: storage_app_redis
    image: "redis:6.2.6"
    restart: always
    ports:
    - "16379:6379"

  mailhog:
    container_name: storage_app_mailhog
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1026:1025 # smtp server
      - 8026:8025 # web ui